[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/snake"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
